version: '{build}'  
pull_requests:  
  do_not_increment_build_number: true

branches:  
  only:
  - master

nuget:  
  disable_publish_on_pr: true

build_script:
- ps: Update-AppveyorBuild -Version "15-foo"
- ps: .\Build.ps1

test: off  

artifacts:  
- path: .\artifacts\**\*.nupkg
  name: NuGet
  
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: '2K5EQwNNYpt5GMRVKxHTihZO2MZCUSbsngmYo63XPO73UoX0n7INS/4OGIrZ3mMe'
  on:
    branch: master
    appveyor_repo_tag: true
